import json
import os
import socket

os.environ.setdefault("AWS_ACCESS_KEY_ID", "testing")
os.environ.setdefault("AWS_SECRET_ACCESS_KEY", "testing")
os.environ.setdefault("AWS_SESSION_TOKEN", "testing")
os.environ.setdefault("AWS_REGION", "eu-west-1")
os.environ.setdefault("SECRET_KEY", "test-secret-key-not-for-production")
os.environ.setdefault("TABLE_NAME", "WebshopTableTest")
os.environ.setdefault("GSI1_NAME", "GSI1")
os.environ.setdefault("EVENT_BUS_NAME", "webshop-event-bus-test")
os.environ.setdefault("FLASK_DEBUG", "1")

import boto3  # noqa: E402
import pytest  # noqa: E402
from moto.server import ThreadedMotoServer  # noqa: E402

from app.config import (  # noqa: E402
    EVENT_BUS_NAME,
    INVENTORY_QUEUE_NAME as INVENTORY_QUEUE,
    NOTIFICATION_QUEUE_NAME as NOTIFICATION_QUEUE,
    PAYMENT_QUEUE_NAME as PAYMENT_QUEUE,
    TABLE_NAME,
)
from app.repositories.single_table import put_products  # noqa: E402
from scripts.bootstrap_local_infra import ensure_table_exists  # noqa: E402
from scripts.seed_products import load_products  # noqa: E402


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


@pytest.fixture(scope="session")
def moto_server_url():
    port = _free_port()
    server = ThreadedMotoServer(ip_address="127.0.0.1", port=port)
    server.start()
    url = f"http://127.0.0.1:{port}"
    yield url
    server.stop()


@pytest.fixture(scope="session", autouse=True)
def aws_endpoints(moto_server_url):
    os.environ["DYNAMODB_ENDPOINT_URL"] = moto_server_url
    os.environ["EVENTS_ENDPOINT_URL"] = moto_server_url
    os.environ["SQS_ENDPOINT_URL"] = moto_server_url
    os.environ["COGNITO_IDP_ENDPOINT_URL"] = moto_server_url
    return moto_server_url


@pytest.fixture(scope="session")
def cognito_pool(aws_endpoints):
    # Pool id/client id/secret are generated by moto at runtime (unlike the
    # queue names, which are fixed constants) -- see app/config.py's comment
    # on why app/auth/cognito.py reads these from os.environ per-call rather
    # than as frozen import-time constants.
    client = boto3.client("cognito-idp", region_name="eu-west-1", endpoint_url=aws_endpoints)
    pool_id = client.create_user_pool(PoolName="webshop-test-pool")["UserPool"]["Id"]
    app_client = client.create_user_pool_client(
        UserPoolId=pool_id,
        ClientName="webshop-test-client",
        GenerateSecret=True,
        ExplicitAuthFlows=["ALLOW_USER_PASSWORD_AUTH", "ALLOW_REFRESH_TOKEN_AUTH"],
    )["UserPoolClient"]
    client.create_group(UserPoolId=pool_id, GroupName="Admins")

    os.environ["COGNITO_USER_POOL_ID"] = pool_id
    os.environ["COGNITO_CLIENT_ID"] = app_client["ClientId"]
    os.environ["COGNITO_CLIENT_SECRET"] = app_client["ClientSecret"]
    return pool_id


@pytest.fixture(scope="session")
def dynamodb_table(aws_endpoints):
    ensure_table_exists()
    put_products(load_products())
    return TABLE_NAME


def _create_queue_and_rule(
    events_client, sqs_client, queue_name: str, rule_name: str, event_pattern: dict
) -> str:
    queue_url = sqs_client.create_queue(QueueName=queue_name)["QueueUrl"]
    queue_arn = sqs_client.get_queue_attributes(QueueUrl=queue_url, AttributeNames=["QueueArn"])[
        "Attributes"
    ]["QueueArn"]

    events_client.put_rule(
        Name=rule_name,
        EventBusName=EVENT_BUS_NAME,
        EventPattern=json.dumps(event_pattern),
        State="ENABLED",
    )
    events_client.put_targets(
        Rule=rule_name,
        EventBusName=EVENT_BUS_NAME,
        Targets=[{"Id": f"{rule_name}-target", "Arn": queue_arn}],
    )
    return queue_url


@pytest.fixture(scope="session")
def eventbridge_bus_and_queues(aws_endpoints):
    events_client = boto3.client("events", region_name="eu-west-1", endpoint_url=aws_endpoints)
    sqs_client = boto3.client("sqs", region_name="eu-west-1", endpoint_url=aws_endpoints)

    events_client.create_event_bus(Name=EVENT_BUS_NAME)

    base_pattern = {"source": ["webshop.orders"], "detail-type": ["OrderPlaced"]}
    notification_pattern = {**base_pattern, "detail": {"notify": [True]}}

    queue_urls = {
        PAYMENT_QUEUE: _create_queue_and_rule(
            events_client, sqs_client, PAYMENT_QUEUE, "payment-rule", base_pattern
        ),
        INVENTORY_QUEUE: _create_queue_and_rule(
            events_client, sqs_client, INVENTORY_QUEUE, "inventory-rule", base_pattern
        ),
        NOTIFICATION_QUEUE: _create_queue_and_rule(
            events_client, sqs_client, NOTIFICATION_QUEUE, "notification-rule", notification_pattern
        ),
    }
    return queue_urls


@pytest.fixture(autouse=True)
def _drain_sqs_queues_after_test(request):
    # eventbridge_bus_and_queues is session-scoped (recreating the bus/rules/queues per
    # test would be slow), so without this, messages published by one test's checkout(s)
    # sit undeleted and accumulate across the whole session. Once more than
    # MaxNumberOfMessages=10 pile up, a later test's receive_message call can return an
    # arbitrary subset that doesn't include the message it's looking for (SQS standard
    # queues make no ordering/completeness guarantee). Purging after every test that
    # touched the queues keeps each test's queue state isolated.
    yield
    if "eventbridge_bus_and_queues" in request.fixturenames:
        queue_urls = request.getfixturevalue("eventbridge_bus_and_queues")
        sqs_client = boto3.client(
            "sqs", region_name="eu-west-1", endpoint_url=request.getfixturevalue("aws_endpoints")
        )
        for queue_url in queue_urls.values():
            sqs_client.purge_queue(QueueUrl=queue_url)


@pytest.fixture()
def app(dynamodb_table, eventbridge_bus_and_queues, cognito_pool):
    from app.main import create_app

    flask_app = create_app()
    flask_app.config["TESTING"] = True
    return flask_app


@pytest.fixture()
def client(app):
    return app.test_client()
